version: '3'

services:
  nginx-rtmp:
    build: .
    runtime: nvidia
    ports:
      - 1935:1935
      - 8080:80
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs